### ISSUE TITLE
How do I use this integration?

### ISSUE THREAD

**Issue by viktak** [msekoranja/emsc-hacs-repository#2]
I installed it using HACS, can see it in the `custom_components/emscrss` directory, but I can't see a sensor created in HA after restart.
Any special steps required?

**Comment by julianrinaldi** [comment]
Add a new sensor to your configuration:

```
sensor:
  - platform: emscrss
    name: Earthquakes
    radius: 300
    magnitude: 3.0
```
